// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdo2RJwEvn2fmgBa0QVDNij_YdioBknX8',
    appId: '1:848970339950:web:9b55c5fa3b9f225697387f',
    messagingSenderId: '848970339950',
    projectId: 'marketplace-61682',
    authDomain: 'marketplace-61682.firebaseapp.com',
    storageBucket: 'marketplace-61682.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6aF-1WYovnhm0bU6S8Vyo0XRlqETemi8',
    appId: '1:848970339950:android:1f0dabb02548a47897387f',
    messagingSenderId: '848970339950',
    projectId: 'marketplace-61682',
    storageBucket: 'marketplace-61682.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZ5WOwXtTeVdexzy-8NEtamWPD-vz7Uk',
    appId: '1:848970339950:ios:4c002ea0319f2bba97387f',
    messagingSenderId: '848970339950',
    projectId: 'marketplace-61682',
    storageBucket: 'marketplace-61682.firebasestorage.app',
    iosBundleId: 'com.example.marketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbZ5WOwXtTeVdexzy-8NEtamWPD-vz7Uk',
    appId: '1:848970339950:ios:4c002ea0319f2bba97387f',
    messagingSenderId: '848970339950',
    projectId: 'marketplace-61682',
    storageBucket: 'marketplace-61682.firebasestorage.app',
    iosBundleId: 'com.example.marketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdo2RJwEvn2fmgBa0QVDNij_YdioBknX8',
    appId: '1:848970339950:web:7df317d966d3071197387f',
    messagingSenderId: '848970339950',
    projectId: 'marketplace-61682',
    authDomain: 'marketplace-61682.firebaseapp.com',
    storageBucket: 'marketplace-61682.firebasestorage.app',
  );
}
